### ISSUE TITLE
suboptimal dependencies for apache 2.4

### ISSUE THREAD

**Issue by thoughtafter** [phusion/passenger_apt_automation#10]
debian_specs/passenger/control.erb

libapache2-mod-passenger depends on an mpm which are obsolete with apache 2.4. There are a few solutions and off the top of my head I'm not sure what would be best but it is weird as a sysadmin to see an mpm installation with apache 2.4 so this should be fixed.

**Comment by FooBarWidget** [comment]
Looks like the dependency should now be "apache2 (>= 2.4)".
