### ISSUE TITLE
Please provide packages for Debian Stretch/testing

### ISSUE THREAD

**Issue by paulmenzel** [phusion/passenger_apt_automation#20]
For people wanting to use Debian and Ruby 2.3, required by Ruby on Rails 5, it’d be great if you could provide packages for Debian Stretch/testing.

**Comment by FooBarWidget** [comment]
We only provide packages for stable Debian versions. Debian testing is a moving target so it's too much work for us to support it until it is declared stable.

If you want to test Rails 5 and Ruby 2.3 then there is no need to use Debian testing. Simply install Ruby from source (or from RVM, or from rbenv, or whatever). The Passenger Debian packages do not require Ruby to come from APT.
