### ISSUE TITLE
Sync nginx configuration with Debian upstream

### ISSUE THREAD

**Issue by drybjed** [phusion/passenger_apt_automation#7]
In Debian `nginx` package, from version 1.6.1, [Debian is using upstream configuration files](http://sources.debian.net/src/nginx/1.6.2-5~bpo70%2B1/debian/nginx-common.NEWS/#L20), which includes `/etc/nginx/fastcgi.conf`.

Unfortunately, `nginx` package from Phusion does not have this change and `fastcgi.conf` file, which prevents me from using it on installation where other applications might need it. Is there a chance to add `/etc/nginx/fastcgi.conf` configuration file to the Phusion `nginx` package?

**Comment by FooBarWidget** [comment]
I've been looking into the new upstream Debian packages but there have been *a lot* of changes. They removed Naxsi, they moved all kinds of stuff, etc. Unlike Debian, we're trying to make packages that support even older distros such as Debian 6 and Ubuntu 10.04. As the newer Debian packages diverge more and more from the older packages, it becomes increasingly harder for us to maintain the packages.

We'll try to merge the fastcgi.conf thing, but no guarantees. It depends a lot on the priority of other open issues.

But why can't you use our packages? Our packages simply supply default configuration files, but we don't overwrite whatever custom config files you have. You can simply drop your own nginx.conf and fastcgi.conf in /etc/nginx.

**Comment by drybjed** [comment]
Thanks for the quick response, @FooBarWidget :-) I'm actually using Passenger via [debops.nginx](https://github.com/debops/ansible-nginx/) Ansible role. To keep as much compatibility with Debian as possible, I don't provide `/etc/nginx/fastcgi.conf` via the role to not create unnecessary conflicts.

I actually [check the nginx version](https://github.com/debops/ansible-nginx/blob/master/templates/etc/nginx/sites-available/php5.conf.j2#L58-L62) to handle the case of `fastcgi.conf` not being there in the first place. However since your `nginx` package, despite being >1.6.1, does not have that file, it caused an error. I suppose that I could add another condition and check if nginx flavor I use is either official one or Passenger, and that should solve my problem. However, it would be nice to see it included in your package to avoid similar issues when other software starts to use `/etc/nginx/fastcgi.conf` more.

**Comment by FooBarWidget** [comment]
If you're using Ansible, wouldn't it be better for you to control the entire /etc/nginx directory instead of checking the version number?

**Comment by drybjed** [comment]
Perhaps, with time... Right now I don't need to modify all of the files in `/etc/nginx/`, so I would need to divert them and then push my own copies which would be the same... So that's not useful to have for the moment.

I'm checking `nginx` version to support `nginx` package from Debian Wheezy, which does not have `SPDY` support - in that case I need to omit it from the generated configuration files. Adding another condition based on the nginx version and type of server I'm currently using (normal, Passenger), was easy. It's already included in the role. :)

**Comment by FooBarWidget** [comment]
This change has been implemented as part of the support for Debian 8 and Ubuntu 15.04.
